 <!-- Introduction Row -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Qui sommes nous
                    <small></small>
                </h1><br/>
                <p>Nous sommes très heureux de vous acceuillir et vous présenter notre équipe.<br/>
                Equipe jeune, dynamique et motivée</p>
            </div>
        </div>

        <!-- Team Members Row -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Notre équipe</h2>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
                <h3>M. DIENG
                    <small>Directeur Général</small>
                </h3>
                <p>Directeur général</p>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
                <h3>M. SAMB
                    <small>Responsable Pédagogique</small>
                </h3>
                <p>Chargé de la gestion des formations ....</p>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
                <h3>M. GUEYE
                    <small>Adminstrateur</small>
                </h3>
                <p>Gestion des enmplois du temps</p>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
                <h3>Mme GAYE
                    <small>Institutrice</small>
                </h3>
                <p>Cours de français et d'anglais</p>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
                <h3>M. FALL
                    <small>Professeur</small>
                </h3>
                <p>Professeur arabat et récitation du courant</p>
            </div>
            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/200x200" alt="">
                <h3>Mme NDIAYE
                    <small>Conseillère  pédagogique</small>
                </h3>
                <p>Chargée de conseiller et orienter les élèves </p>
            </div>
        </div>

