<?php //var_dump( $this->form); die;?>
<div class="row">
	<address>
		<strong>Complex Islamique Mawloud</strong><br>
		Rue 27 Nimzat<br>
		Nimzat, Rufique Sénégal<br>
		<abbr title="Phone">Tél Mobile :</abbr> +221 77 524 45 78
	</address>
</div>
<div class="row">
	<h1 class="text-center">Pour nous contacter</h1>
		<br/>
		<div class="col-sm-12">
		<form action="<?php echo $this->url(array('controller' => 'nous-contacter', 'action' => 'index')) ?>" method="post" >
			<div class="row form-group">
				<div class="col-xs-5 col-xs-offset-1">
				<input id="prenom" class="form-control" type="text" name="prenom" placeholder='Prénom*' required></div>

				<div class="col-xs-5">
					<input id="nom" class="form-control" type="text" name="nom"  placeholder='Nom*' required>
				</div>
			</div>
			<div class="row form-group">
				<div class="col-xs-5 col-xs-offset-1">
					<input class="form-control" type="email" name="email"  placeholder='Email*' required></div>
				<div class="col-xs-5">
					<input class="form-control" type="phone" name="phone"  placeholder='Numéro de téléphone*' required>
				</div>
			</div>
			<div class="row form-group">
				<div class="col-xs-10 col-xs-offset-1">
				<input name ="siteWeb" id="siteWeb" class="form-control" type="homepage" placeholder='Site Web*'></div>
			</div>
			<div class="row form-group">
				<div class="col-xs-10 col-xs-offset-1"><textarea name="message"  id="message" class="form-control" rows="5"  placeholder='Votre message' required></textarea></div>
			</div>
			<div class="row form-group">
				<div class="col-xs-11"><button class="btn  btn-lg btn-success pull-right">Envoyer</button></div>
			</div>
		</form>
	</div>
</div>
