<?php //var_dump( $this->form); die;?>
<div class="row">
	<div class="col-md-6">
		<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d7717.82805070064!2d-17.271406474808476!3d14.717452556442089!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xec19fc137980b03%3A0x2f17ba47ed9b2b44!2zUnVmaXNxdWUsIFPDqW7DqWdhbA!5e0!3m2!1sfr!2sfr!4v1416592869966" width="250" height="200" frameborder="0" style="border:0"></iframe>
	</div>
	<div class="col-md-6">
			<h3>Complex Islamique Mawloud</h3>
			<span>Rue 27 Nimzat<br>Nimzat, Rufique Sénégal<br>
				<abbr title="Phone">Tél Mobile :</abbr> +221 77 524 45 78
			</span>
	</div>
</div>
<div class="row">
	<h1 class="text-center">Pour nous contacter</h1>
		<br/>
		<div class="col-sm-12">
		<form action="<?php echo $this->url(array('controller' => 'nous-contacter', 'action' => 'index')) ?>" method="post" >
				<div class="row form-group">
					<div class="col-xs-5 col-xs-offset-1">
					<input id="prenom" class="form-control" type="text" name="prenom" placeholder='Prénom*' required></div>

					<div class="col-xs-5">
						<input id="nom" class="form-control" type="text" name="nom"  placeholder='Nom*' required>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-xs-5 col-xs-offset-1">
						<input class="form-control" type="email" name="email"  placeholder='Email*' required></div>
					<div class="col-xs-5">
						<input class="form-control" type="phone" name="phone"  placeholder='Numéro de téléphone*' required>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-xs-10 col-xs-offset-1">
					<input name ="siteWeb" id="siteWeb" class="form-control" type="homepage" placeholder='Site Web'></div>
				</div>
				<div class="row form-group">
					<div class="col-xs-10 col-xs-offset-1"><textarea name="message"  id="message" class="form-control" rows="5"  placeholder='Votre message*' required></textarea></div>
				</div>
				<div class="form-group"> 
				    <div class="col-md-12">
				      <div class="checkbox">
				        <label><input id="enCopie" name="enCopie" type="checkbox" value="0"> M'envoyer une copie </label>
				      </div>
				    </div>
			  	</div>
			  	<!-- div class="form-group"> 
				    <div class="col-md-10 col-xs-offset-1 captcha">
				     <?php //echo $this->form->captcha; ?>
				    </div>
			  	</div -->

				<div class="row form-group">
					<div class="col-xs-11"><button class="btn  btn-lg btn-success pull-right">Envoyer</button></div>
				</div>
		</form>
	</div>
</div>
