
<div class="row">
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-2.jpg'); ?>" alt="...">
          <div class="carousel-caption">
          	<h3>Bienvenue</h3>
          </div>
        </div>
        <div class="item">
          <img src="<?php echo $this->baseUrl('/images/slideshow/photo1.jpg'); ?>" alt="...">
          <div class="carousel-caption">
          	<h3>Complexe Islamique</h3>
          </div>
        </div>
        <div class="item">
          <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-3.jpg'); ?>" alt="..."> <!-- image taille 1200x315 -->
          <div class="carousel-caption">
          	<h3>Daara Mawloud</h3>
          </div>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div> <!-- Carousel -->
</div>
<br/>
<br/>



<div class="row">
        
        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="">
              <div class="caption">
                <h4>Thumbnail label</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>
                <p><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-default btn-xs" role="button">Lire la suite...</a></p>
            </div>
          </div>
        </div>

        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="">
              <div class="caption">
                <h4>Thumbnail label</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>
                <p><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-default btn-xs" role="button">Lire la suite...</a></p>
            </div>
          </div>
        </div>

        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="">
              <div class="caption">
                <h4>Thumbnail label</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>
                <p><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-default btn-xs" role="button">Lire la suite...</a></p>
            </div>
          </div>
        </div>

        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="">
              <div class="caption">
                <h4>Thumbnail label</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>
                <p><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-default btn-xs" role="button">Lire la suite...</a></p>
            </div>
          </div>
        </div>
        
      </div><!-- End row -->

    