 <section class="row articles">
	<div class="col-xs-4 col-sm-3 col-md-2"><img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="Tigre">
		<h5>Titre articles</h5>
		<span>L'article parle de bcp de choses L'article parle de bcp de choses L'article parle de bcp de choses</span>
		<a href="#" class="btn"></a>
		<a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-success btn-mini">Lire la suite...</a>

	</div>
	<div class="col-xs-4 col-sm-3 col-md-2"><img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="Tigre"></div>
	<div class="col-xs-4 col-sm-3 col-md-2"><img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="Tigre"></div>
	<div class="col-xs-4 col-sm-3 col-md-2"><img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="Tigre"></div>
	<div class="col-xs-4 col-sm-3 col-md-2"><img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="Tigre"></div>
	<div class="col-xs-4 col-sm-3 col-md-2"><img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="Tigre"></div>
	<div class="col-xs-4 col-sm-3 col-md-2"><img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="Tigre"></div>
	<div class="col-xs-4 col-sm-3 col-md-2"><img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="Tigre"></div>
	<div class="col-xs-4 col-sm-3 col-md-2"><img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="Tigre"></div>
	<div class="col-xs-4 col-sm-3 col-md-2"><img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="Tigre"></div>
	<div class="col-xs-4 col-sm-3 col-md-2"><img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="Tigre"></div>
	<div class="col-xs-4 col-sm-3 col-md-2"><img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="Tigre"></div>
</section>