<div class="row">
        
        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="">
              <div class="caption">
                <h4>Thumbnail label</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>
                <p><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-default btn-xs" role="button">Lire la suite...</a></p>
            </div>
          </div>
        </div>

        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="">
              <div class="caption">
                <h4>Thumbnail label</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>
                <p><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-default btn-xs" role="button">Lire la suite...</a></p>
            </div>
          </div>
        </div>

        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="">
              <div class="caption">
                <h4>Thumbnail label</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>
                <p><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-default btn-xs" role="button">Lire la suite...</a></p>
            </div>
          </div>
        </div>

        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="">
              <div class="caption">
                <h4>Thumbnail label</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>
                <p><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-default btn-xs" role="button">Lire la suite...</a></p>
            </div>
          </div>
        </div>
        


        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="">
              <div class="caption">
                <h4>Thumbnail label</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>
                <p><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-default btn-xs" role="button">Lire la suite...</a></p>
            </div>
          </div>
        </div>


        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="">
              <div class="caption">
                <h4>Thumbnail label</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>
                <p><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-default btn-xs" role="button">Lire la suite...</a></p>
            </div>
          </div>
        </div>


        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="">
              <div class="caption">
                <h4>Thumbnail label</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>
                <p><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-default btn-xs" role="button">Lire la suite...</a></p>
            </div>
          </div>
        </div>


        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-22.jpg'); ?>" alt="">
              <div class="caption">
                <h4>Thumbnail label</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>
                <p><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'lire',)); ?>" class="btn btn-default btn-xs" role="button">Lire la suite...</a></p>
            </div>
          </div>
        </div>
      </div><!-- End row -->