
        <div class="row">
            <div class="col-sm-8">
                <h2>Nos Services</h2>
                <p></p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et molestiae similique eligendi reiciendis sunt distinctio odit? Quia, neque, ipsa, adipisci quisquam ullam deserunt accusantium illo iste exercitationem nemo voluptates asperiores.</p>
                <p>
                    <a class="btn btn-default btn-lg" href="#">Suite... &raquo;</a>
                </p>
            </div>
            <div class="col-sm-4">
                <h2>Nous contacter</h2>
                <address>
                    <strong>Daara Mawlood</strong>
                    <br>Nimzat
                    <br>Rufisque Sénégal
                    <br>
                </address>
                <address>
                    <abbr title="Phone"> Port.: </abbr>(221) 77 608 14 95
                    <br>
                    <abbr title="Email"> Email: </abbr> <a href="mailto:#">complexe@daara.com</a>
                </address>
            </div>
        </div>
        <!-- /.row -->

        <hr>


        <div class="row">
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-4.jpg'); ?>" alt="">
                <h2>Internat</h2>
                <p>These marketing boxes are a great place to put some information. These can contain summaries of what the company does, promotional information, or anything else that is relevant to the company. These will usually be below-the-fold.</p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-3.jpg'); ?>" alt="">
                <h2>Apprendre par coeur le coran</h2>
                <p>The images are set to be circular and responsive. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="<?php echo $this->baseUrl('/images/slideshow/example-slide-350-2.jpg'); ?>" alt="">
                <h2>Education Physique</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
            </div>
        </div>