<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Daara Mawlood</title>
  <?php echo $this->headLink()->appendStylesheet('css/bootstrap.css') ?>
  <?php echo $this->headLink()->appendStylesheet('css/bootstrap-theme.css') ?>
  <?php echo $this->headLink()->appendStylesheet('css/justified-nav.css') ?>
  <?php echo $this->headLink()->appendStylesheet('css/jquery.bxslider.css') ?>
  <?php echo $this->headLink()->appendStylesheet('css/main.css') ?>


  <?php echo $this->headScript()->prependFile( $this->baseUrl('/js/jquery.js')) ?>
  <?php echo $this->headScript()->prependFile( $this->baseUrl('/js/bootstrap.js')) ?>
  <?php echo $this->headScript()->prependFile( $this->baseUrl('/js/jquery.bxslider.min.js')) ?>
  <?php echo $this->headScript()->prependFile( $this->baseUrl('/js/main.js')) ?>

    <style>
    /* Prevents slides from flashing */
    #slides {
      /*display:none;*/
    }
  </style>


  <script>
    $(function(){
      $("#slides").slidesjs({
        width: 940px,
        height: 528px
      });
    });
  </script>
</head>
<body>
	<div class='container'>
		<div class="row">
			<div class="col-xs-12 header">
				<div class="row firt_head">
					<div class="col-sm-3"><a href="#"><img  class="img-responsive"src="<?php echo $this->baseUrl('/images/daara_logo.png'); ?>"></a></div>
					<div class="col-sm-6 titre-site" >
						DAARA MODERNE INTERNAT
							<br/>
							ECOLE FRANCO – ARABE
					</div>
					<div class="col-sm-3 header-contact" >
						<p class="cell"><img src="http://daaramawloud.free.fr/wp-content/themes/business-pro/images/call-us.png" class="call-us">&nbsp; Tel: 77608 14 95 / 77 646 31 28</p>
					</div>
				</div>
    
      <div class="masthead">
        <!-- h3 class="text-muted">Project name</h3 -->
        <div role="navigation">
          <ul class="nav nav-justified">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Projects</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Downloads</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
      </div>
          </div>
			</div>
		</div>

		<div class="row middle-content">
			<div class="col-md-12">
				<?php echo $this->layout()->content ?>
			</div>
		</div>
		<div class="row footer_mine">
			<div class="col-md-12 last-in-footer">Complexe Islamique Mawlood - Siège Social Nimzat - Tel: 77608 14 95 / 77 646 31 28 </div>
		</div>
	</div>
 
 
</body>
</html>